{% set name = "lb-nightly-db" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-db-{{ version }}.tar.gz
  sha256: dc37b1218fcdfcfe358400248ac1cd672912c06b7b4dc4cdbb2962a15fc31960

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - cloudant >=2.14.0,<3.0.0
    - lb-nightly-configuration >=0.1.4,<0.2.0
    - python >=3.6,<4.0

test:
  imports:
    - lb
    - lb.nightly.db
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lb-nightly-db/
  summary: Database access layer for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maszyman
